char * convert_to_uppercase(char * sentence);
char convert_char_to_uppercase(char c);
char * shift_left(char * sentence);
//void cipher_decrypt(char * sentence);
//void cipher_decrypt(FILE *output, char_queue_t* encrypted_contents, char_queue_t* dictionary);
// void read_each_line();
void read_file(char * file, char * ch);
void uppercase_to_file();
//int word_is_in_dictionary(char * dictionary, char * word);
int number_of_lines(char * file);
//char_queue_t* load_dictionary_to_linkedlist();
//char_queue_t* load_encrypted_to_linkedlist();
//int check_dictionary(char_queue_t* dictionary, char* string);
//int check_string(char_queue_t* dictionary, char* string);